[package]
name = "rdb-parser"
version = "0.1.0"
authors = ["NMDanny <nmdanny@gmail.com>"]

[dependencies]
nom = { version =  "3.2.1", features = ["verbose-errors"]}
byteorder = "^1"
serde = "^1"
failure = "^0.1"
lzf = "^0.3"